---
name: Config-XPath
version: 0.11
author:
  - 'Paul Evans E<lt>leonerd@leonerd.org.ukE<gt>'
abstract: |-
  a module for retrieving configuration data from XML files
  by using XPath queries
license: perl
requires:
  Error: 0.15
  XML::XPath: 0
build_requires:
  Test::Exception: 0
  Test::More: 0
provides:
  Config::XPath:
    file: lib/Config/XPath.pm
    version: 0.11
  Config::XPath::BadConfigException:
    file: lib/Config/XPath.pm
    version: 0.11
  Config::XPath::ConfigNotFoundException:
    file: lib/Config/XPath.pm
    version: 0.11
  Config::XPath::Exception:
    file: lib/Config/XPath.pm
    version: 0.11
  Config::XPath::NoDefaultConfigException:
    file: lib/Config/XPath.pm
    version: 0.11
  Config::XPath::Reloadable:
    file: lib/Config/XPath/Reloadable.pm
    version: 0.11
generated_by: Module::Build version 0.26
